### ISSUE TITLE
Dungeon Bug

### ISSUE THREAD

**Issue by kylaawood** [Wyomarus/Wayfinder#6]
Other dungeons seem unaffected but City of Threads the compass doesn't dynamically move. Stays wherever it was last positioned.

**Comment by kylaawood** [comment]
I encountered the same bug in City of Echoes, may be an Azj -Kahet issue

**Comment by wyomarus** [comment]
Thank you for taking the time to report. I hope you are enjoying the add on. 

I don't think there is a way to get coordinates inside an instance (at least relative to the rest of the world.) It's just not something that Blizzard exposes. 

I will add a check to see if the player is in an instance and hide the compass banner.

**Comment by wyomarus** [comment]
@kylaawood Thank you again for the report. I hope that you find this fix (v1.0.0-alpha.6) acceptable. If not, no worries, feel free to reopen this issue or a new one, if preferred.
